# Tell Travis you want a Python environment to test in
language: python
sudo: false
# List the versions of Python you'd like to test against
python:
 - "2.7"
 - "3.4"
 - "3.5"
# List the versions of Django you'd like to test against
env:
 - DJANGO_VERSION=1.8.7
 - DJANGO_VERSION=1.9
# Tell it the things it will need to install when it boots
install:
   # Install whatever version of Django that's listed above
   # Travis is currently working on
 - pip install -q Django==$DJANGO_VERSION
 - pip install pyflakes pep8 coverage python-coveralls
 - python setup.py install
# Tell Travis how to run the test script itself
script:
 - pep8 softhyphen
 - pyflakes softhyphen
 - coverage run setup.py test
# Report coverage results to coveralls.io
after_success:
 - coveralls
